apiVersion: v1
kind: Service
metadata:
  name: profile-service
spec:
  selector:
    app: profile-service
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 3002
  type: {{ .Values.service.type }}
